In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4,5,6]
array=np.array(l1)

In [3]:
array

array([1, 2, 3, 4, 5, 6])

In [4]:
type(array)

numpy.ndarray

In [10]:
arr1=np.array([[1,2,3],[5,4,3],[7,8,9]])
arr1

array([[1, 2, 3],
       [5, 4, 3],
       [7, 8, 9]])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(np.arange(1,10))

numpy.ndarray

In [14]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [20]:
np.arange(11,20,2)

array([11, 13, 15, 17, 19])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.random.rand(10)

array([0.91039641, 0.19033017, 0.26687597, 0.77056931, 0.01339785,
       0.4607482 , 0.41266615, 0.09738559, 0.67799795, 0.91723253])

In [35]:
np.random.randn(10)

array([-0.38237435, -1.26364445,  0.52786389,  0.32190543, -0.625358  ,
        0.51278692,  0.34740247, -1.1921958 ,  0.79858922, -1.03172506])

In [38]:
np.random.randint(1,10,5)

array([1, 3, 9, 5, 2])

In [43]:
np.random.rand(4,6)

array([[0.6821844 , 0.28949879, 0.60437267, 0.60523043, 0.07191918,
        0.83173403],
       [0.95764107, 0.67901245, 0.04653067, 0.55728214, 0.81984201,
        0.90776195],
       [0.09607324, 0.09492095, 0.8322473 , 0.06664428, 0.87673841,
        0.4583611 ],
       [0.91876862, 0.9411626 , 0.10539556, 0.47574187, 0.70405272,
        0.76756784]])

In [44]:
np.random.randn(4,4)

array([[-0.71365533,  0.00358957,  0.36984676, -0.90816656],
       [-0.96852693,  0.09777854,  0.35612029,  0.76902054],
       [ 0.38960121,  0.95216215, -0.47167902,  1.78120211],
       [ 0.93519262,  0.0145435 , -0.35249234,  0.85845335]])

In [46]:
np.random.randint(1,50,6).reshape(2,3)

array([[38, 32, 43],
       [ 5,  5, 26]])

In [48]:
arr1=np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:
arr1.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
np.random.rand(1,100)

array([[0.01619361, 0.10461195, 0.75785615, 0.0372975 , 0.51309844,
        0.07727343, 0.82488392, 0.185554  , 0.27102022, 0.46350069,
        0.43830995, 0.79468163, 0.09086539, 0.89088714, 0.71220602,
        0.84704965, 0.0916803 , 0.27783523, 0.82011041, 0.30900765,
        0.85840699, 0.12373457, 0.13140744, 0.42299515, 0.28340613,
        0.1231012 , 0.24334042, 0.76719817, 0.12895276, 0.67386855,
        0.23017391, 0.80733094, 0.25205235, 0.52064093, 0.98391899,
        0.95608381, 0.44422261, 0.05545602, 0.72115305, 0.07055156,
        0.27624887, 0.6452395 , 0.44543713, 0.85436554, 0.09819031,
        0.55610632, 0.115566  , 0.08795575, 0.3464317 , 0.20869061,
        0.06610986, 0.30653072, 0.83003232, 0.10588917, 0.08613698,
        0.92123747, 0.69844852, 0.32073435, 0.56580232, 0.75470227,
        0.06514583, 0.86957227, 0.60925037, 0.65556168, 0.89734912,
        0.18953038, 0.1414099 , 0.78674252, 0.52587155, 0.17132046,
        0.76994108, 0.31199294, 0.18180097, 0.81

In [54]:
np.random.rand(1,100).max

<function ndarray.max>

In [56]:
np.random.rand(1,100).max()

0.9966414992817066

In [57]:
np.random.rand(1,100).min()

0.03142686299887987

In [58]:
np.random.rand(1,100).argmax()

63

In [59]:
np.random.rand(1,100).argmin()

8

In [61]:
np.random.rand(1,100).shape

(1, 100)

In [63]:
np.random.rand(1,100).dtype

dtype('float64')

In [68]:
arr1=np.random.randn(4,5)
arr1

array([[ 0.85547939,  0.3602633 , -0.54725531,  0.23372079,  1.72232872],
       [-1.92604029, -0.93658334,  1.69822594, -1.93030396,  0.64165056],
       [ 0.21676514,  0.46723339, -1.21758479,  0.76937228, -0.0375325 ],
       [-1.97568169,  0.32962883, -0.57627066,  0.07801504, -0.59468112]])

In [69]:
arr2=np.random.randn(4,5)
arr2

array([[ 0.69571513,  0.67062143,  0.14990568, -0.27585139,  0.14712318],
       [-0.51267334,  0.12892304, -2.28614248, -0.09749976, -1.87385456],
       [ 1.22938826, -0.7398667 ,  0.48772994,  0.84824871, -0.68398624],
       [ 1.78917463,  0.8892033 ,  0.88751302, -1.14535188, -0.60327599]])

In [70]:
arr1+arr2

array([[ 1.55119452,  1.03088473, -0.39734962, -0.0421306 ,  1.86945189],
       [-2.43871362, -0.80766031, -0.58791654, -2.02780372, -1.23220401],
       [ 1.4461534 , -0.2726333 , -0.72985485,  1.617621  , -0.72151874],
       [-0.18650706,  1.21883214,  0.31124237, -1.06733685, -1.19795711]])

In [71]:
arr1-arr2

array([[ 0.15976427, -0.31035813, -0.69716099,  0.50957218,  1.57520554],
       [-1.41336695, -1.06550638,  3.98436842, -1.8328042 ,  2.51550512],
       [-1.01262312,  1.20710009, -1.70531474, -0.07887643,  0.64645374],
       [-3.76485632, -0.55957447, -1.46378368,  1.22336692,  0.00859487]])

In [72]:
arr1/arr2

array([[ 1.22964036,  0.53720815, -3.65066414, -0.84727067, 11.70671237],
       [ 3.75685674, -7.26467017, -0.74283469, 19.7980389 , -0.34242282],
       [ 0.17631952, -0.63151024, -2.49643231,  0.90701262,  0.05487318],
       [-1.10424196,  0.37070131, -0.64930952, -0.06811447,  0.98575301]])

In [73]:
arr1//arr2

array([[ 1.,  0., -4., -1., 11.],
       [ 3., -8., -1., 19., -1.],
       [ 0., -1., -3.,  0.,  0.],
       [-2.,  0., -1., -1.,  0.]])

In [74]:
arr1*arr2

array([[ 0.59516995,  0.24160029, -0.08203668, -0.06447221,  0.25339447],
       [ 0.9874295 , -0.12074717, -3.88238645,  0.18820416, -1.20235982],
       [ 0.26648852, -0.34569043, -0.59385256,  0.65261905,  0.02567171],
       [-3.53483956,  0.29310705, -0.51144771, -0.08935467,  0.35875684]])

In [76]:
arr1**2

array([[7.31844994e-01, 1.29789644e-01, 2.99488372e-01, 5.46254088e-02,
        2.96641620e+00],
       [3.70963118e+00, 8.77188359e-01, 2.88397133e+00, 3.72607338e+00,
        4.11715436e-01],
       [4.69871273e-02, 2.18307042e-01, 1.48251273e+00, 5.91933712e-01,
        1.40868870e-03],
       [3.90331816e+00, 1.08655167e-01, 3.32087871e-01, 6.08634584e-03,
        3.53645636e-01]])

In [79]:
1/arr1*2

array([[  2.33787045,   5.55149529,  -3.65460137,   8.55721897,
          1.16121852],
       [ -1.03839988,  -2.13542128,   1.1776996 ,  -1.03610625,
          3.11696138],
       [  9.22657568,   4.28051598,  -1.64259607,   2.59952177,
        -53.28714851],
       [ -1.01230882,   6.06743041,  -3.47059142,  25.63608379,
         -3.36314695]])

In [82]:
np.sqrt(arr1)

C:\Users\madhu\AppData\Local\Temp\ipykernel_18660\3299852782.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[0.92492129, 0.60021937,        nan, 0.48344678, 1.31237522],
       [       nan,        nan, 1.30315998,        nan, 0.80103093],
       [0.46558044, 0.68354473,        nan, 0.87713869,        nan],
       [       nan, 0.57413311,        nan, 0.27931172,        nan]])

In [83]:
np.exp(arr1)

array([[2.35250189, 1.43370686, 0.57853554, 1.26329172, 5.59754839],
       [0.14572408, 0.39196476, 5.46424487, 0.14510409, 1.89961371],
       [1.24205236, 1.59557375, 0.29594407, 2.15841096, 0.96316311],
       [0.13866675, 1.39045194, 0.56199032, 1.08113891, 0.55173848]])

In [84]:
np.sin(arr2)

array([[ 0.64093453,  0.62147296,  0.14934488, -0.27236624,  0.146593  ],
       [-0.49050864,  0.12856619, -0.75486625, -0.09734535, -0.95442825],
       [ 0.94228416, -0.67418946,  0.46862173,  0.75012343, -0.63188761],
       [ 0.97625007,  0.77657005,  0.77550401, -0.91085539, -0.56734323]])

In [85]:
np.cos(arr2)

array([[ 0.76759555,  0.78343561,  0.98878517,  0.96219366,  0.98919689],
       [ 0.87143633,  0.99170093, -0.65587876,  0.99525066, -0.29844047],
       [ 0.33481422,  0.73855844,  0.88339893,  0.66129784,  0.77506003],
       [-0.21664673,  0.63003092,  0.63134264,  0.41272565,  0.82348143]])

In [86]:
np.tan(arr1)

array([[ 1.1509914 ,  0.37670348, -0.60933513,  0.23807158, -6.54866096],
       [ 2.69554391, -1.35945797, -7.8049471 ,  2.6607008 ,  0.74711252],
       [ 0.22022525,  0.5044903 , -2.71243643,  0.96845114, -0.03755014],
       [ 2.3333747 ,  0.34211021, -0.64985127,  0.0781737 , -0.6763567 ]])

In [89]:
np.log(arr2)

C:\Users\madhu\AppData\Local\Temp\ipykernel_18660\2430268246.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr2)


array([[-0.36281501, -0.39955049, -1.89774895,         nan, -1.91648511],
       [        nan, -2.04853966,         nan,         nan,         nan],
       [ 0.2065167 ,         nan, -0.71799342, -0.16458139,         nan],
       [ 0.58175441, -0.11742938, -0.11933208,         nan,         nan]])

In [91]:
arr3=np.random.randn(10,10)
arr3

array([[ 0.01626877,  0.49495401,  1.31306093,  0.62151088, -0.64638222,
        -0.40777207,  0.82581019, -0.57706481,  1.09223681, -0.05241972],
       [-2.16448178, -0.40005507,  0.04949651, -0.3483127 ,  2.02652191,
        -0.48789304,  0.00728113,  0.65347816, -1.46099605,  1.4032086 ],
       [-1.27163233,  0.06257347, -1.11278957,  2.25699822,  0.12627004,
        -0.28039099, -0.40884618, -0.51695271,  0.02121626,  0.35475414],
       [ 0.22052753, -0.21280054, -0.25912809, -0.89150912, -0.46832846,
        -0.55104281, -0.17854901, -0.30145824,  2.23520432,  1.35053058],
       [-1.94979639,  0.98580589, -0.76819487,  1.50752802,  0.0146464 ,
        -0.00923033,  0.97133405,  0.37477768, -0.5405747 ,  0.03012055],
       [ 0.15609072, -0.3406117 ,  2.02855635,  0.75928175, -0.63664345,
        -1.06719919, -0.50395711, -1.36774238,  0.41667832, -0.88602921],
       [ 0.18964272, -0.11298404,  0.92576928, -0.31034409, -0.47836201,
         1.57488657, -0.18935012, -0.27949917

In [92]:
arr3.shape

(10, 10)

In [95]:
arr3[4]

array([-1.94979639,  0.98580589, -0.76819487,  1.50752802,  0.0146464 ,
       -0.00923033,  0.97133405,  0.37477768, -0.5405747 ,  0.03012055])

In [96]:
arr3[4,0]

-1.9497963920556503

In [97]:
arr3[0:3,1:3]

array([[ 0.49495401,  1.31306093],
       [-0.40005507,  0.04949651],
       [ 0.06257347, -1.11278957]])

In [103]:
arr4=np.arange(0,30).reshape(6,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [105]:
arr4[3:5,2:4]

array([[17, 18],
       [22, 23]])

In [107]:
arr4[0:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [113]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
type(my_matrix)

list

In [121]:
arr5=np.array([[1,2,3],[4,5,6]])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
arr6=arr5.copy()

In [123]:
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
arr5[0,0]=100

In [127]:
arr5

array([[100,   2,   3],
       [  4,   5,   6]])

In [129]:
arr1

array([[ 0.85547939,  0.3602633 , -0.54725531,  0.23372079,  1.72232872],
       [-1.92604029, -0.93658334,  1.69822594, -1.93030396,  0.64165056],
       [ 0.21676514,  0.46723339, -1.21758479,  0.76937228, -0.0375325 ],
       [-1.97568169,  0.32962883, -0.57627066,  0.07801504, -0.59468112]])

In [130]:
arr1>0.2

array([[ True,  True, False,  True,  True],
       [False, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [False,  True, False, False, False]])

In [131]:
arr1[arr1>0.3]

array([0.85547939, 0.3602633 , 1.72232872, 1.69822594, 0.64165056,
       0.46723339, 0.76937228, 0.32962883])

In [133]:
arr1[arr1<0.6]

array([ 0.3602633 , -0.54725531,  0.23372079, -1.92604029, -0.93658334,
       -1.93030396,  0.21676514,  0.46723339, -1.21758479, -0.0375325 ,
       -1.97568169,  0.32962883, -0.57627066,  0.07801504, -0.59468112])

In [135]:
arr2[arr2>2]

array([], dtype=float64)

In [136]:
arr2>2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [138]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [140]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [142]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [144]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
np.random.rand(1)

array([0.60485454])

In [161]:
np.random.randn(25)

array([-1.0796201 , -0.54512346, -1.03415842, -0.06281993, -0.76575564,
        1.42743395, -0.45677731,  0.54621904, -0.38693156, -0.59618624,
       -0.61043053, -1.14449139,  0.4871458 ,  0.82299685, -0.01907845,
       -0.66069965, -0.59842333, -0.07423324,  1.33596356, -1.54381051,
       -0.09565179, -1.44003605, -0.11681843, -0.36909219, -2.00066369])

In [162]:
np.random.randn(25,25)

array([[-8.89508547e-01,  8.55148425e-01, -2.73053718e-01,
        -1.00875167e+00,  8.96261997e-01,  5.63309330e-01,
         1.05520083e+00,  1.48016454e+00, -9.77840362e-01,
         4.21915525e-02,  5.97988582e-01, -6.07833028e-01,
         1.27932423e-01,  1.12244639e+00, -2.54923551e-01,
         1.06559753e+00, -1.12762984e+00,  5.35907653e-01,
        -1.71995336e+00,  3.21921001e-01,  5.98918545e-01,
        -2.70629703e-01, -4.68428224e-01,  5.90202135e-01,
         7.89030648e-01],
       [ 1.50886670e-02,  5.92278485e-01, -8.65161936e-01,
        -5.31657203e-01, -2.05844024e+00,  1.11061625e-01,
        -1.35258650e+00,  1.35078371e-01,  4.20048813e-01,
        -8.82006294e-01,  4.05250378e-01, -1.42068355e+00,
        -2.58749024e+00,  1.09124961e-01,  7.50014192e-01,
         2.04480909e-01, -1.44601909e+00,  5.41806269e-01,
        -2.96619258e-02, -1.20373451e+00, -4.15926213e-01,
        -1.45589045e+00, -4.98204843e-01,  2.72608115e-02,
         1.03208921e+00],
    

In [165]:
np.arange(0,100).reshape(10,10)/100

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [169]:
arr8=np.arange(0,25).reshape(5,5)
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [171]:
arr8[2:,2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [172]:
arr8[4,0]

20

In [179]:
arr8[:3,2:3]

array([[ 2],
       [ 7],
       [12]])

In [181]:
arr8.sum()

300

In [182]:
arr8.std()

7.211102550927978

In [184]:
arr8.sum(axis=0)

array([50, 55, 60, 65, 70])

In [185]:
arr8.sum(axis=1)

array([ 10,  35,  60,  85, 110])